#
# Cookbook:: yaml_cookbook_apache
# Recipe:: default
#
# Copyright:: 2020, The Authors, All Rights Reserved.
resources:
    - type: "package"
      name: "httpd"
    - type: "template"
      name: "/var/www/html/index.html"
      source: "index.html.erb"
    - type: "service"
      name: "httpd"
      action: 
        - enable
        - start